// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotelService.proto

// Protobuf Java Version: 4.26.1
package raf.hotelreservation.grpc;

public interface HotelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Hotel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 stars = 2;</code>
   * @return The stars.
   */
  int getStars();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double distanceFromCenter = 4;</code>
   * @return The distanceFromCenter.
   */
  double getDistanceFromCenter();
}
