// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto
// Protobuf Java Version: 4.26.1

package raf.hotelreservation.grpc;

public final class PaymentServiceOuterClass {
  private PaymentServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      PaymentServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PaymentService.proto\";\n\016PaymentRequest" +
      "\022\020\n\010clientID\030\001 \001(\t\022\027\n\017availableAmount\030\002 " +
      "\001(\001\"2\n\017PaymentResponse\022\017\n\007success\030\001 \001(\010\022" +
      "\016\n\006amount\030\002 \001(\0012G\n\016PaymentService\0225\n\016Pro" +
      "cessPayment\022\017.PaymentRequest\032\020.PaymentRe" +
      "sponse\"\000B\035\n\031raf.hotelreservation.grpcP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PaymentRequest_descriptor,
        new java.lang.String[] { "ClientID", "AvailableAmount", });
    internal_static_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PaymentResponse_descriptor,
        new java.lang.String[] { "Success", "Amount", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
