// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto

// Protobuf Java Version: 4.26.1
package raf.hotelreservation.grpc;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   * @return The clientID.
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   * @return The bytes for clientID.
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>double availableAmount = 2;</code>
   * @return The availableAmount.
   */
  double getAvailableAmount();
}
