// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentService.proto

// Protobuf Java Version: 4.26.1
package raf.hotelreservation.grpc;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  double getAmount();
}
