// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HotelService.proto

// Protobuf Java Version: 4.26.1
package raf.hotelreservation.grpc;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   * @return The clientID.
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   * @return The bytes for clientID.
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>double maxDistance = 3;</code>
   * @return The maxDistance.
   */
  double getMaxDistance();

  /**
   * <code>int32 minStars = 4;</code>
   * @return The minStars.
   */
  int getMinStars();
}
