// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto
// Protobuf Java Version: 4.26.1

package raf.hotelreservation.grpc;

public final class ReservationServiceOuterClass {
  private ReservationServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ReservationServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ReservationService.proto\"[\n\022Reservatio" +
      "nRequest\022\020\n\010clientID\030\001 \001(\t\022\017\n\007hotelID\030\002 " +
      "\001(\t\022\021\n\tstartDate\030\003 \001(\003\022\017\n\007numDays\030\004 \001(\005\"" +
      "U\n\013Reservation\022\017\n\007hotelID\030\001 \001(\t\022\021\n\tstart" +
      "Date\030\002 \001(\003\022\017\n\007numDays\030\003 \001(\005\022\021\n\tdateToPay" +
      "\030\004 \001(\0032G\n\022ReservationService\0221\n\014reserveH" +
      "otel\022\023.ReservationRequest\032\014.ReservationB" +
      "\035\n\031raf.hotelreservation.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReservationRequest_descriptor,
        new java.lang.String[] { "ClientID", "HotelID", "StartDate", "NumDays", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "HotelID", "StartDate", "NumDays", "DateToPay", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
