// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReservationService.proto

// Protobuf Java Version: 4.26.1
package raf.hotelreservation.grpc;

public interface ReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientID = 1;</code>
   * @return The clientID.
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 1;</code>
   * @return The bytes for clientID.
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string hotelID = 2;</code>
   * @return The hotelID.
   */
  java.lang.String getHotelID();
  /**
   * <code>string hotelID = 2;</code>
   * @return The bytes for hotelID.
   */
  com.google.protobuf.ByteString
      getHotelIDBytes();

  /**
   * <code>int64 startDate = 3;</code>
   * @return The startDate.
   */
  long getStartDate();

  /**
   * <code>int32 numDays = 4;</code>
   * @return The numDays.
   */
  int getNumDays();
}
